name: Black Check
on: [push, pull_request]

permissions:
  contents: read      

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - run: pip install black

      - name: Run Black in check mode
        run: black --check --diff .
