name: Black Auto Format
on: [push, pull_request]

permissions:
  contents: write          

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4          
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install black
      - run: black .
      - name: Commit & push if changed
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Auto‑format code with Black"
            git push
          fi
